apiVersion: workloads.x-k8s.io/v1alpha2
kind: RoleBasedGroup
metadata:
  name: qwen3-8b
spec:
  roles:
  - minReadySeconds: 0
    name: inference
    podManagementPolicy: Parallel
    replicas: 1
    servicePorts:
    - name: http
      port: 30000
      targetPort: 30000
      protocol: TCP
    standalonePattern:
      template:
        metadata:
          labels:
            rbg.workloads.x-k8s.io/source: rbgcli
        spec:
          # tolerations:
          # - key: "node-role.alibabacloud.com/lingjun"
          #   operator: "Exists"
          #   effect: "NoSchedule"
          containers:
          - args:
            - --model-path
            - /models/qwen-qwen3-8b/main
            - --served-model-name
            - qwen3-8b
            - --host
            - 0.0.0.0
            - --port
            - "30000"
            command:
            - python
            - -m
            - sglang.launch_server
            env:
            - name: SGLANG_MODEL_PATH
              value: /models/qwen-qwen3-8b/main
            image: lmsysorg/sglang:v0.5.10.post1
            imagePullPolicy: IfNotPresent
            name: sglang
            ports:
            - containerPort: 30000
              name: http
              protocol: TCP
            resources:
              limits:
                cpu: "2"
                memory: 48Gi
                nvidia.com/gpu: "1"
              requests:
                cpu: "2"
                memory: 48Gi
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /models
              name: model-storage
          volumes:
          - emptyDir:
              medium: Memory
              sizeLimit: 16Gi
            name: shm
          - name: model-storage
            persistentVolumeClaim:
              claimName: oss1-lj
    workload:
      apiVersion: workloads.x-k8s.io/v1alpha2
      kind: RoleInstanceSet
